### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#1]
If unhandled exceptions occur, it should be logged somewhere.
This should be elaborated.

**Comment by janLo** [comment]
I recommend to run a sentry instance.

**Comment by lukasjuhrich** [comment]
Thanks, this looks like a very powerful tool to work with. Although it may cause some work to set up, it will most certainly pay off and I think we should use it in the long run.

**Comment by janLo** [comment]
Commit 630facf3f23ce4e3fe56da54d5248023b417722a introduced a fixed RotatingFileHandler as log handler. As the target for this application is a docker container this seems a bit useless because it only gives the file system some work without a real possibility to review the logs.

As mentioned above I recommend something like a sentry instance to aggregate exceptions.

For request logging the log handler should be configureable. I suggest to use one of the formats python.logging provides (see https://docs.python.org/2/library/logging.config.html). So we can use stdout and let docker handle the log or use syslog directly. There is no need to keep local logfiles within a stateless container in production.

**Comment by lukasjuhrich** [comment]
I closed this issue although there *might* be different things to add / improve regarding the logging, but these should be handled in more special, new issues.
