### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by peetCreative** [agdsn/sipa#11]
Write Dockerfile and add necessary files to run the application in an Dockercontainer

**Comment by lukasjuhrich** [comment]
# Current status:
The dockerfile is valid and should theoratically run.
# Further Things to do:
* Elaborate a nice standard way to set up an nginx instance in a docker container
* Copy files necessary for the latter into a directory like `docker_setup` and track it in git
* Add documentation in a way that someone who never used docker is able to run this configuration and create a running instance of sipa.

**Comment by janLo** [comment]
I think the nginx frontend is not in the scope of this project because in production the frontend proxy will be responsible for more than this project. Simply add a example server section to the README.

The added with 665237460823455790718e3674d562f2c1f1d102 is not ready for production. Some basic issues are::

* It is derived from `phusion/baseimage` - I think we should use official images.
* I think `python:2.7` is the better choice as we install system wide pathon packages via pip packages and the image ensure to not conflict with debians own python packages by removing them.
* The logging location is not marked as VOLUME (and there should be no local logging at all, see #1 )
The image should be configureable from outside the container (ENV or config via volume) to prevent pushing of images with builtin credentials.
* The uwsgi process should be pid1 to prevent overhead
* The uwsgi call should be configureable (processes/threads/...)
* Static files should be defivered directly by uwsgi
* There is no need to be root insinde the container - you can directly specify USER sipa in the Dockerfile

**Comment by sebschrader** [comment]
I agree with @janLo . Running nginx is totally unnecessary. For development the Flask internal web server is sufficient and for production deployment an application server like uwsgi or similar is the appropriate choice. I fully agree with the configurability bits, too.

Using something else than uwsgi as PID 1 is certainly not a big overhead, but if uwsgi correctly reaps children it should be used of course. I assume @peetCreative chose `phusion/baseimage` because of this well-known blog post:
https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by janLo** [comment]
Even if uwsgi leaks some zombies, their pcb should be less overhead than the init this image uses. I also think we do not need syslog, an openssh-server, cron and logrotate, nano _and_ vim in a single-service container.

In this case uwsgi already have excellent child-handling. Just use the [--master](http://uwsgi-docs.readthedocs.org/en/latest/Options.html#master) option.

**Comment by sebschrader** [comment]
Don't get me wrong. I'm not saying we should use the `phusion/baseimage` as it is indeed too heavy.

But saying leaking zombies is not a problem is just plain wrong, every leak is a problem eventually.

If uwsgi is handling reaping than that's perfect, the documentation you referenced is not very elaborate.

**Comment by janLo** [comment]
See http://uwsgi-docs.readthedocs.org/en/latest/Management.html for more information

**Comment by lukasjuhrich** [comment]
We have to think about a nice way to provide the configuration information, since the basic docker container shoud be built from the *clean* repository state, and therefore not contain the actual `config.py`.

**Comment by sebschrader** [comment]
It's very simple: The config should be used during runtime or startup of the container and not be needed during *build* time of the image.

**Comment by janLo** [comment]
What is the best option in a coreos deployment?

**Comment by lukasjuhrich** [comment]
Because “Dockerize the application” is something I consider fixed in Sipa's current state, I will close this issue. Discussion will go on as always, but for more specific questions to come, there should be a new issue for each of them.
