### ISSUE TITLE
Make changing of MAC addresses a two-step procedure

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#115]
Because currently, the warning is just an additional field on the bottom of the form, it is quite easy to ignore it. Because the content is rather important, it would be better to enforce confirming t ohave read the field, which would be a two-step procedure.

Refs @sebschrader s comment in #108.

**Comment by lukasjuhrich** [comment]
Implementing this is not possible in an elegant manner, since the entered MAC-address has to be remembered just until the next request, from that exact user. I do not see that this feature is really important, so I'm closing.

**Comment by sebschrader** [comment]
Ever heard of hidden input fields?

**Comment by toothstone** [comment]
I'm strongly opposed to dropping this entirely, since there have been multiple discussions on this topic and imho it was consensus that we have to implement this if we decide to give users  the possibility to change the MAC on their own. Therefore this is not your decision to make and I would rather recommend to reopen the discussion and get a decision from our division meeting.

**Comment by toothstone** [comment]
(Given that there really is no technical solution to this.)

**Comment by sebschrader** [comment]
Let's keep it technical before talking about such things in our meetings.

**Comment by toothstone** [comment]
> Let's keep it technical before talking about such things in our meetings.
I second that :) I really can't imagine there is no way to do this.
