### ISSUE TITLE
Enable login with mail address as username 

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#128]
Most members don't really know their username, and will try to login with the same username/password combination they use for the web mailers. Accepting these in SIPA as well would be more user friendly.

**Comment by lukasjuhrich** [comment]
What do you mean by “username/password combination they use for the web mailers”? Do you mean their assigned mail address, or their redirected one? I do not think that this is what users do. Mostly, they try to use the `user_id` instead of the username.

**Comment by toothstone** [comment]
I had in mind the assigned mail address.

`user_id` is another option, and could probably be supported as well.

**Comment by lukasjuhrich** [comment]
I would find it very unpleasing to check multiple things on multiple datasources (whose backends work differently) instead of the username, whose _very purpose_ is the identification for a login process. This just makes the code more complicated in a place where it should not be.

Instead of patching sipa because users do not know what the login is, I think it is better to fix that missing knowledge by including a hint where to find the username.

**Comment by sebschrader** [comment]
You don't need to check multiple things. You should just remove the domain suffix, if one was provided. We should accept arbitrary mail suffixes though, e.g. <correct-wh2-username>@gmail.com should not work, neither should <correct-wh2-username>@wh9.tu-dresden.de

Additional bonus points would be awarded if some JavaScript magic on the client side would select the correct dormitory in the dormitory dropdown for the user if she types in the an mail address of the dormitories domain

**Comment by janLo** [comment]
Just provide an option to the user to receive the login information via email.
