### ISSUE TITLE
Add dormitory to mail context

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/sipa#302]
Since recently, our mail queues have been merged, we would not know which dormitory has been selected / the user lives in.  This information should be added to the mail.

**Comment by lukasjuhrich** [comment]
(test)

**Comment by toothstone** [comment]
Afaik the contact form currently inserts the selected dormitory into the mail - or do you mean something else?

**Comment by sebschrader** [comment]
I think he means setting headers, such as `X-OTRS-Queue`, `X-OTRS-CustomerNo`, etc. so that the ticket system puts the mail in the right queue and associates it with the right user, if possible.

See the [OTRS documentation](https://doc.otrs.com/doc/manual/admin/stable/en/html/administration.html#table-of-x-otrs-headers) for a list of all possible headers and see also #357.

**Comment by lukasjuhrich** [comment]
@deepshitgoeshere @Paktosan do you still think this is relevant? Because the main motivator for that was the distinction between the different backends we had, which now only consist of `{pycroft}`.

**Comment by deepshitgoeshere** [comment]
I don't see this as relevant anymore, now that we only use one backend.

Most of the problems we encounter in support are independent of dormitory, and for everything else, either a quick look to the sidebar or a search in Pycroft will give you the needed information.

**Comment by lukasjuhrich** [comment]
Good to hear. Thanks for the quick reply!
