### ISSUE TITLE
Zeunerstraße: Missing traffic gauge

### ISSUE THREAD

**Issue by chlewe** [agdsn/sipa#334]
During the support session of the Wundtstraße on 08/05/2017, a member of our network approached me and reported that the traffic gauge has never worked for him in the Zeunerstraße 1f dormitory.
Is that a bug that needs fixing or a feature that is not meant to work for the Zeunerstraße at all?

**Comment by lukasjuhrich** [comment]
@chlewe The Zeunerstraße IP ranges are [included](https://github.com/agdsn/sipa/blob/develop/sipa/model/wu/__init__.py#L42) in sipa, so there should not be any problems. The last time such incidents came to my attention, the problem was that a VPN has been used. If possible, could you verify that the user accesses sipa with an IP address of the correct subnet?

**Comment by lukasjuhrich** [comment]
Due to no further activity and no new symptoms I will close this issue.
