### ISSUE TITLE
display traffic data on gauge in a readable way

### ISSUE THREAD

**Issue by toothstone** [agdsn/sipa#6]
The spent traffic is currently displayed in arbitrary units (percentage?), which imho is not what a user wants to know. 
I would propose simply displaying the current credit, preferably on a fixed scale up to the maximum credit to provide a quick way to check it.

Users in need of more detailed information (e.g. because they are very low on credit) can still look it up in the usersuite.

**Comment by lukasjuhrich** [comment]
@toothstone That is false, since the limits “0-100” are the default values which are automatically set by the gauge plugin. Setting the max value to 0 causes exactly this.
For the non-standard behaviour (with data) see the picture:
![screenie](https://cloud.githubusercontent.com/assets/10060406/7216610/b7bc9b96-e605-11e4-8316-a943b1880851.png)

**Comment by toothstone** [comment]
Ok, that looks way better, but since a lot of people will visit the page from external IPs we might want to make that view look better as well.
￼ 
However, I still dont think the normal user is interested in the spent traffic, people just want to see at a glance how soon they will run out.

**Comment by lukasjuhrich** [comment]
With “how soon they will run out”, do you imply a “time left” approach, or a “traffic left”? Because how much traffic is left is just what the gauge displays. When running out of traffic, the bar almost completely covers the chart and is automatically gets more and more red (see (this)[http://justgage.com/] ⇒ Demos ⇒ Show color by sector)

**Comment by toothstone** [comment]
Time left is obviously pretty much impossible, as I stated in my first I would just prefer to have credit displayed instead of spent volume. A fixed scale would be faster to read and probably easier to understand for newbies. But lets just wait for feedback from real users, if ppl complain we can easily change it.

**Comment by sebschrader** [comment]
I too suggest traffic volume left instead of traffic volume spent as this conveys the information the user is searching for in the best manner. Gauges typically resemble fuel and the like, which is good analogy for the traffic they have. 

The maximum of the gauge should be static and not dynamic (I don't how it's done currently). Set it always to the maximum amount of traffic one could save, i.e. currently 63 GiB.
