### ISSUE TITLE
Division-dependent data in content pages

### ISSUE THREAD

**Issue by lightning1** [agdsn/sipa#60]
The bank account data should be hidden, until a dormitory is selected. This should prevent transactions to an account that does not match the division of the user.

**Comment by lukasjuhrich** [comment]
Which financial data are you talking about? Please give me a link or something similar.

Are you sure this is something concerning SIPA and not the content alone?

**Comment by lightning1** [comment]
@lukasjuhrich The content does not support dynamic elements, but only static pages. At the last board meeting there was a common request to hide the bank account details, until you select (e.g. in a dropdown box) the dormitory you live in.
This should prevent members from using the first bank account on the homepage.

**Comment by lukasjuhrich** [comment]
@lightning1 I think I have a suitable Idea: How about some way to provide separate _box_ (panel, whatever) for this? This way, one does not need to invent some way to „search-and-replace“ every whole `.md` file for some pattern (e.g. `$$division$$`), but rather can define the box content in a _separate file_, perhaps in a completely separate folder like `content/boxes`.

The box would have to be placed on the top/bottom of the file, because else one faces the same problem. This way, some identification name could be given in the markdown header.

On the other hand: Perhaps there is some way to utilize jinji2 intelligently? I mean this _is_ some kind of templating problem, isn't it?

**Comment by lightning1** [comment]
@lukasjuhrich i think you are going too far. We just need scripted content for one dropdown box. I imagined something like the traffic gauge (at the same position), but just displayed on the finance page.
Maybe we can include the amount a user has to pay there, too. The current solution is quiet confusing.

**Comment by lukasjuhrich** [comment]
This seems rather special. So you would want to change the sidebar if one exact content page is displayed? And what about the contacts (although another issue, perhaps)? They are already taking space there.

I am very skeptical about this. The user knows the sidebar, and the conceptual meaning of it is to display general information which would be of use regardless of the things displayed in the content area.

And besides, a whole IBAN is quite long compared to the sidebar.
