### ISSUE TITLE
Contact form: From- and To-addresses

### ISSUE THREAD

**Issue by lightning1** [agdsn/sipa#70]
Currently the contact form is only able to send mails to @wh2 accounts, but has to support @agdsn.de addresses.
The mail-field in the user form should not be editable, but the mail forward may be linked there.

**Comment by lukasjuhrich** [comment]
Although it is possible to send the mails directly to `support@agdsn.de`, this is not an active mailing list. Wouldn't it be more feasible to use the already established `support@whx.tu-dresden.de` addresses? This is what I will do in order to leave the contact form in a _working_ state.

If in the long run, a global `support@agdsn.de` mailing list will have been established, you may reopen the issue and tell me so.
