### ISSUE TITLE
Hiding the Emailaddresses

### ISSUE THREAD

**Issue by Janluak** [agdsn/sipa#78]
To avoid spam the email adresses should not be shown directly on the webpage but instead only be used in contact forms.

**Comment by lukasjuhrich** [comment]
To narrow this question down a bit, we must elaborate a way to produce some content in a delayed manner, such that it cannot be fetched automatically.

Note also that such content would have be displayed _outside_ any content page, because anything else would result in a very complicated (or at least not beautiful) solution I would like to avoid.

**Comment by lightning1** [comment]
@Janluak at least after logging in the mail adresses can be shown on the webpage.

The contact form is not visible to the public right now, you have to log in first. To make the form public accessible, we have to add a captcha.

**Comment by toothstone** [comment]
I don't think this is necessary. The @wh2 addresses have been plain-text
public for ages, and all of us are on enough more-or-less public lists
to receive spam forever, no matter what we do with SIPA.

The only real effect of any address-hiding will be reduced usability,
e.g. for people relying on having a full history available in their
client, using voice-over and mailto-recognition, on mobile devices...

Also I don't think it's very representative for the AG DSN to only offer
a cheesy webform, in total disregard for _the_ standard of communication
in the intertubes, especially in technical matters. What about signing,
encryption, attachments?

**Comment by mmarx** [comment]
^- This.

**Comment by lukasjuhrich** [comment]
mmarx: no spam plz :(

**Comment by Janluak** [comment]
nearly no spam with @wh12 with hiding the address shows that it is quite affective. The usability might be lower, yet is still good enough to be working smoothly (again check with @wh12)

**Comment by lukasjuhrich** [comment]
Alright, no trolling now.

@Janluak Although this discussion surely has to be lead in an appropriate place other than this, I just want to mention the following:

>  - The objective of this entire exercise is not to reduce the amount of spam you get in your email, but the amount of spam you manually have to remove from your inbox.
>  - Email obfuscation is a constant battle to come up with ever sophisticated bot-proof, human-readable encoding, and is a drain on the productivity of both the creator, and the correspondent.
>  - “Almost any email address that you use for any length of time eventually becomes widely enough known that you should assume all the spammers have it.”
>  - “The convenience of stable, easily copy-pastable email addresses” wins over trying to hide from the spambots.

taken from [here](http://www.howtogeek.com/129673/does-email-address-obfuscation-actually-prevent-spam/?PageSpeed=noscript).
Note also that we _don't have significant spam_ at `@wh2` addresses _either_ (at most once per month, varying slightly), since the metric is __spam you have to remove manually__.

With this in mind, I plead to not use anything costing the user more clicks / redirects than necessary and use some easy obfuscating method such as `display:none` (in the link given above, there is a graph undermining its effectiveness).

**Comment by MarauderXtreme** [comment]
@Janluak told me to write this here.
We recently got a message from one of our partners. They stated that the contact over the website did not work. Since that issue was closed shouldn't that work?

**Comment by lukasjuhrich** [comment]
@MarauderXtreme Alright, I have quite bad news, there has been a typo in the mail address (`suppor@`). I will be sending a test mail in the next few minutes.

Besides that, I will try to recover the messages from the log entries, and will add an apology in the news.

The problem here was that I thought I tested it – which I did, but by sending a support mail to the hss to verify the address, and not by using the contact form. This should not have happened.
